[package]
name = "tstring-html"
description = "HTML parser-first renderer for PEP 750 template strings"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tstring-format-doc = { version = "0.1.0", path = "../tstring-format-doc-rs" }
tstring-syntax.workspace = true
